MVC2024/Controllers/SerieController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC2024.Models;

namespace MVC2024.Controllers
{
    public class SerieController : Controller
    {
        public Contexto Contexto { get; } //Se crea un objeto de la clase contexto, para poder usar sus métodos (acceder a la base de datos)

        public SerieController(Contexto contexto)
        {
            Contexto = contexto;
        }
        // GET: SerieController
        public ActionResult Index()
        {
            List<SerieModelo> lista = Contexto.Series.Include(s => s.Marca).ToList(); //crea una lista de marcas y la rellena con los datos de la tabla marcas. El include especificamos que le añadimos un objeto de otra clase, el campo Marca de SerieModelo.cs
            return View(lista); //devuelve la vista
        }

        public ActionResult Listado(int id)
        {
            //Contexto.Marcas.Find(id).LasSeries = Contexto.Series.Where(s => s.MarcaId == id).ToList();
            //return View(Contexto.Marcas.Find(id)); //devuelve la vista
            return View(Contexto.Marcas.Include(m => m.LasSeries).FirstOrDefault(m => m.Id == id));
        }

        // GET: SerieController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: SerieController/Create
        public ActionResult Create()
        {
            ViewBag.MarcaId = new SelectList(Contexto.Marcas, "Id", "Nom_Marca");
            return View();
        }

        // POST: SerieController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SerieModelo serie)
        {
            Contexto.Series.Add(serie);
            Contexto.Database.EnsureCreated();
            Contexto.SaveChanges();
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SerieController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: SerieController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SerieController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: SerieController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

MVC2024/Views/Marca/Create.cshtml
@model MVC2024.Models.MarcaModelo

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>MarcaModelo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nom_Marca" class="control-label">Marca</label>
                <input asp-for="Nom_Marca" class="form-control" />
                <span asp-validation-for="Nom_Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC2024/Views/Marca/Desplegable.cshtml
<h1>Desplegable</h1>

@Html.DropDownList("LasMarcas", new List<SelectListItem>{
    new SelectListItem{Text="Opel", Value="1", Selected=true},
    new SelectListItem{Text="Ferrari", Value="2"},
     new SelectListItem{Text="Mercedes", Value="3"}
})
@Html.DropDownList("Marcas", "Seleccione una marca")

<select id="unasmarcas" name="unasmarcas">
    @foreach (var item in ViewBag.Marcas2)
    {
        <option value="@item.ID">@item.Nom_Marca</option>
    }
</select>

MVC2024/Views/Marca/Index.cshtml
@model IEnumerable<MVC2024.Models.MarcaModelo>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<p>
<a asp-action="Listado">Listado</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nom_Marca)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nom_Marca)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

MVC2024/Views/Marca/Listado.cshtml
@model IEnumerable<MVC2024.Models.MarcaModelo>

@{
    ViewData["Title"] = "Listado";
}

<h1>Listado</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Marca")
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <a asp-action="Listado" asp-controller="Serie" asp-route-id="@item.Id">@item.Nom_Marca</a> <!-- Controller Serie (sin el controller)-->
            </td>
        </tr>
}
    </tbody>
</table>